#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_autodiscover_outlook:
  path: /autodiscover/autodiscover.xml
  controller: App\Controller\AutoDiscoverController::generate
  defaults:
    type: 'outlook'
    preset: null

app_autodiscover_thunderbird:
  path: /mail/config-v1.1.xml
  controller: App\Controller\AutoDiscoverController::generate
  defaults:
    type: 'thunderbird'
    preset: null

app_autodiscover_ios:
  path: /email.mobileconfig
  controller: App\Controller\AutoDiscoverController::generate
  defaults:
    type: 'ios'
    preset: null

app_autodiscover_auto:
  path: /generate/{type}/{preset}
  controller: App\Controller\AutoDiscoverController::generate
  defaults:
    preset: null
